@faker_api_HostAddress = http://localhost:5250
@from = 2025-04-01T00:00:00Z
@until = 2025-04-02T00:00:00Z&

###
GET {{faker_api_HostAddress}}/api/trades?from={{from}}&until={{until}}&commingleId=12345&deliveryId=12345
Accept: application/json


###
GET {{faker_api_HostAddress}}/api/trades/ohlcv?from={{from}}&until={{until}}&commingleId=12345&deliveryId=12345
Accept: application/json

###
GET {{faker_api_HostAddress}}/openapi/v1.json
Accept: application/json
